version: '3.8'

services:
  fastapi:
    build: .
    container_name: company-info-retrieval
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy  
    env_file:
      - .env
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: company_info_cache
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app_network
    volumes:
      - redis_data:/data  
    healthcheck:  
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:  
    driver: local

networks:
  app_network:
    driver: bridge
